POST http://localhost:4444/api/cars/createCar 
content-type: application/json

{
    "brand" : "Mercedes",
    "modelName" : "AMG One",
    "price" : 2200000
}

###

GET http://localhost:4444/api/cars/getCars HTTP/1.1 