POST http://localhost:2222/api/buyers/signUp HTTP/1.1
content-Type: application/json

{
    "name": "dragonite dragon",
    "email": "dragonite@dragon.com",
    "password": "dragonitedragon"
}

###

POST http://localhost:2222/api/buyers/signIn HTTP/1.1
content-type: application/json

{
    "email": "tanish@gupte.com",
    "password": "tanishgupte"
}

###

POST http://localhost:2222/api/buyers/signUp
content-Type: application/json

{
    "name": "tanish gupte",
    "email": "tanish@gupte.com",
    "password": "tanishgupte"
}

###

POST http://localhost:2222/api/buyers/signIn 
content-type: application/json

{
    "email": "dragonite@dragon.com",
    "password": "dragonitedragon"
}

###

POST http://localhost:2222/api/buyers/signUp
content-Type: application/json

{
    "name": "Black Sails",
    "email": "black@sails.com",
    "password": "blacksails"
}

###

GET http://localhost:2222/api/buyers/currentUser/60685e0e2a7ba90728ea339f HTTP/1.1

###

POST http://localhost:2222/api/buyers/signOut

###
DELETE http://localhost:2222/api/buyers/deleteMany HTTP/1.1

###
GET http://localhost:2222/api/buyers/all HTTP/1.1