POST http://localhost:2222/api/buyers/signUp HTTP/1.1
content-Type: application/json

{
    "name": "Rotting Christ",
    "email": "rotting@christ.com",
    "password": "rottingchrist"
}

###

POST http://localhost:2222/api/buyers/signIn 
content-type: application/json

{
    "email": "gupte@tanish.com",
    "password": "tanishgupte"
}

###

POST http://localhost:2222/api/buyers/signUp
content-Type: application/json

{
    "name": "Tanish Gupte",
    "email": "tanish@gupte.com",
    "password": "tanishgupte"
}

###

POST http://localhost:2222/api/buyers/signUp
content-Type: application/json

{
    "name": "Black Sails",
    "email": "black@sails.com",
    "password": "blacksails"
}

###

GET http://localhost:2222/api/ HTTP/1.1

###

DELETE http://localhost:2222/api/buyers/deleteMany HTTP/1.1

###
GET http://localhost:2222/api HTTP/1.1