apiVersion: apps/v1
type: Deployment
metadata: 
  name: mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-buyer
    template:
      metadata:
        labels:
          app: mongo-buyer


